name: action-sha-cache-secondary
on: push
# useful to temporarily disable
# on: workflow_dispatch

jobs:
  fetch-prev-result:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.restore-cache.outputs.result }}
      deploy_sha: ${{ steps.restore-cache.outputs.deploy_sha }}
    steps:
      - id: restore-cache
        uses: parallel-markets/cache-result-action@master
