name: default-ci
# disabling on push
# on: workflow_dispatch
on: push

jobs:
  validate-ref:
    runs-on: ubuntu-latest
    outputs:
      deployable: ${{ steps.check-left-right.outputs.valid }}
    steps:
      - uses: actions/checkout@v3
      - run: git fetch origin
      - id: check-left-right
        run: echo "valid=$(git rev-list --left-right --count $GITHUB_SHA...origin/main | grep -c '^0\s*[0-9]$')" | tee $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'all good'

  deploy:
    needs: [test, validate-ref]
    if: needs.validate-ref.outputs.deployable == '1' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags'))
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying $DEPLOY_REF"
        env:
          DEPLOY_REF: ${{ github.ref }}
