name: optimistic-main
# run full test suite whenever any branch is pushed
# this means we don't run tests when only pushing a tag
on:
  push:
    branches: '*'
# disabling on push
# on: workflow_dispatch

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}

  test-one:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'passing'

  test-two:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'passing also'

  test:
    needs: [code-quality, test-one, test-two]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'all good'

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'deploy staging'
