# Deploys the prod tag, assuming that tests have already been run on main
# You could tag prod before tests have even run and potentially do bad things.
# Requires that you trust what's on main, which requires trusting PR merges.
name: optimistic-prod
on:
  push:
    tags: ['prod', 'demo']

# disabling on push
# on: workflow_dispatch

jobs:
  check-tag-is-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch origin

      - name: Verify tag is equivalent to origin/main
        run: |
          if [[ "${{ github.sha }}" != "$(git rev-parse origin/main)" ]]; then
            echo "${{ github.ref_name }} != main";
            exit 7;
          fi

  deploy:
    needs: check-tag-is-main
    runs-on: ubuntu-latest
    steps:
      - run: echo 'deploy ${{ github.ref_name }}'
