name: tree-cache-main
on: push
# useful to temporarily disable
# on: workflow_dispatch

jobs:
  # Use skip-duplicate-actions@v5 to determine if there's a previous equivalent successful build.
  check-duplicate-run:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
        # https://github.com/fkirc/skip-duplicate-actions/tree/2ab7af90a863e0b3f8ed0d2f5a22989ea94408f0
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@2ab7af90a863e0b3f8ed0d2f5a22989ea94408f0

  # Get the commit SHA of origin/main to ensure we never deploy tags that are not on main
  fetch-main-sha:
    runs-on: ubuntu-latest
    outputs:
      main_sha: ${{ steps.rev-parse-origin-main.outputs.MAIN_SHA }}
    steps:
      - uses: actions/checkout@v3
      - id: rev-parse-origin-main
        run: |
          git fetch origin
          echo "MAIN_SHA=$(git rev-parse origin/main)" >> $GITHUB_OUTPUT

  # An example skippable, test component
  code-quality:
    needs: check-duplicate-run
    if: needs.check-duplicate-run.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'pass'

  # An example skippable, test component
  test-one:
    needs: check-duplicate-run
    if: needs.check-duplicate-run.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'pass'

  # An example skippable, test component
  test-two:
    needs: check-duplicate-run
    if: needs.check-duplicate-run.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      # - run: echo 'fail'; exit 2
      - run: echo 'pass'

  # Aggregate, required status check. Will be skipped if any of the sub-tests fail or are skipped.
  test:
    needs: [code-quality, test-one, test-two]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'all good'

  # Deploy if test passed or if a previous successful run exists.
  deploy:
    needs: [fetch-main-sha, check-duplicate-run, test]
    if: always() && needs.fetch-main-sha.outputs.main_sha == github.sha && (github.ref == 'refs/heads/main' || github.ref == 'refs/tags/prod' || github.ref == 'refs/tags/demo')
    runs-on: ubuntu-latest
    steps:
      - if: needs.test.result != 'success' && needs.check-duplicate-run.outputs.should_skip != 'true'
        run: |
          echo "Refusing to deploy commit! test=${{ needs.test.result }}, check-duplicate-run=${{ needs.check-duplicate-run.outputs.should_skip }}"
          exit 255

      - run: echo "deploy staging"
        if: github.ref == 'refs/heads/main'
      - run: echo "deploy prod"
        if: github.ref == 'refs/tags/prod'
      - run: echo "deploy demo"
        if: github.ref == 'refs/tags/demo'
